.TH MAKEDICT 1 "2006-09-23" "makedict-0.3"
.SH NAME
makedict \- converter from any dictionary format to any
.SH SYNOPSIS
.B makedict
[
.BI options
]
path/to/dictionary
.SH EXAMPLES
makedict -o stardict --work-dir ~/.stardict/dic eng2rus.dsl
.SH BUGS
Email bug reports to dushistov at mail dot ru. Be sure to include the word
"makedict" somewhere in the "Subject:" field.
.SH AUTHORS
Evgeniy A. Dushistov
