/* 
 * WARNING generated automatically by
 * cat ISO-639-2_utf-8.txt | iso_639_2_tbl_to_cpp.py  > lang_tbl_auto.cpp
 * DO not edit
 *
 * To get ISO-639-2_utf-8.txt follow the link
 * http://www.loc.gov/standards/iso639-2/ascii_8bits.html
 * Download the version in UTF-8 encoding. 
*/

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include <cstddef>
#include "lang_tbl.hpp"

void load_iso_639_2_langs()
{
	lang_tbl.push_back(LangTblItem("aar", "aa", "Afar"));
	lang_tbl.push_back(LangTblItem("abk", "ab", "Abkhazian"));
	lang_tbl.push_back(LangTblItem("ace", "", "Achinese"));
	lang_tbl.push_back(LangTblItem("ach", "", "Acoli"));
	lang_tbl.push_back(LangTblItem("ada", "", "Adangme"));
	lang_tbl.push_back(LangTblItem("ady", "", "Adyghe"));
	lang_tbl.push_back(LangTblItem("ady", "", "Adygei"));
	lang_tbl.push_back(LangTblItem("afa", "", "Afro-Asiatic languages"));
	lang_tbl.push_back(LangTblItem("afh", "", "Afrihili"));
	lang_tbl.push_back(LangTblItem("afr", "af", "Afrikaans"));
	lang_tbl.push_back(LangTblItem("ahk", "", "Ahka"));
	lang_tbl.push_back(LangTblItem("ain", "", "Ainu"));
	lang_tbl.push_back(LangTblItem("aka", "ak", "Akan"));
	lang_tbl.push_back(LangTblItem("akk", "", "Akkadian"));
	lang_tbl.push_back(LangTblItem("alb", "sq", "Albanian"));
	lang_tbl.push_back(LangTblItem("ale", "", "Aleut"));
	lang_tbl.push_back(LangTblItem("alg", "", "Algonquian languages"));
	lang_tbl.push_back(LangTblItem("alt", "", "Southern Altai"));
	lang_tbl.push_back(LangTblItem("amh", "am", "Amharic"));
	lang_tbl.push_back(LangTblItem("ang", "", "English, Old (ca.450-1100)"));
	lang_tbl.push_back(LangTblItem("anp", "", "Angika"));
	lang_tbl.push_back(LangTblItem("apa", "", "Apache languages"));
	lang_tbl.push_back(LangTblItem("ara", "ar", "Arabic"));
	lang_tbl.push_back(LangTblItem("arc", "", "Official Aramaic (700-300 BCE)"));
	lang_tbl.push_back(LangTblItem("arc", "", "Imperial Aramaic (700-300 BCE)"));
	lang_tbl.push_back(LangTblItem("arg", "an", "Aragonese"));
	lang_tbl.push_back(LangTblItem("arm", "hy", "Armenian"));
	lang_tbl.push_back(LangTblItem("arn", "", "Mapudungun"));
	lang_tbl.push_back(LangTblItem("arn", "", "Mapuche"));
	lang_tbl.push_back(LangTblItem("arp", "", "Arapaho"));
	lang_tbl.push_back(LangTblItem("art", "", "Artificial languages"));
	lang_tbl.push_back(LangTblItem("arw", "", "Arawak"));
	lang_tbl.push_back(LangTblItem("asm", "as", "Assamese"));
	lang_tbl.push_back(LangTblItem("ast", "", "Asturian"));
	lang_tbl.push_back(LangTblItem("ast", "", "Bable"));
	lang_tbl.push_back(LangTblItem("ast", "", "Leonese"));
	lang_tbl.push_back(LangTblItem("ast", "", "Asturleonese"));
	lang_tbl.push_back(LangTblItem("ath", "", "Athapascan languages"));
	lang_tbl.push_back(LangTblItem("aus", "", "Australian languages"));
	lang_tbl.push_back(LangTblItem("ava", "av", "Avaric"));
	lang_tbl.push_back(LangTblItem("ave", "ae", "Avestan"));
	lang_tbl.push_back(LangTblItem("awa", "", "Awadhi"));
	lang_tbl.push_back(LangTblItem("aym", "ay", "Aymara"));
	lang_tbl.push_back(LangTblItem("aze", "az", "Azerbaijani"));
	lang_tbl.push_back(LangTblItem("bad", "", "Banda languages"));
	lang_tbl.push_back(LangTblItem("bai", "", "Bamileke languages"));
	lang_tbl.push_back(LangTblItem("bak", "ba", "Bashkir"));
	lang_tbl.push_back(LangTblItem("bal", "", "Baluchi"));
	lang_tbl.push_back(LangTblItem("bam", "bm", "Bambara"));
	lang_tbl.push_back(LangTblItem("ban", "", "Balinese"));
	lang_tbl.push_back(LangTblItem("baq", "eu", "Basque"));
	lang_tbl.push_back(LangTblItem("bas", "", "Basa"));
	lang_tbl.push_back(LangTblItem("bat", "", "Baltic languages"));
	lang_tbl.push_back(LangTblItem("bej", "", "Beja"));
	lang_tbl.push_back(LangTblItem("bej", "", "Bedawiyet"));
	lang_tbl.push_back(LangTblItem("bel", "be", "Belarusian"));
	lang_tbl.push_back(LangTblItem("bem", "", "Bemba"));
	lang_tbl.push_back(LangTblItem("ben", "bn", "Bengali"));
	lang_tbl.push_back(LangTblItem("ber", "", "Berber languages"));
	lang_tbl.push_back(LangTblItem("bho", "", "Bhojpuri"));
	lang_tbl.push_back(LangTblItem("bih", "bh", "Bihari languages"));
	lang_tbl.push_back(LangTblItem("bik", "", "Bikol"));
	lang_tbl.push_back(LangTblItem("bin", "", "Bini"));
	lang_tbl.push_back(LangTblItem("bin", "", "Edo"));
	lang_tbl.push_back(LangTblItem("bis", "bi", "Bislama"));
	lang_tbl.push_back(LangTblItem("bla", "", "Siksika"));
	lang_tbl.push_back(LangTblItem("bnt", "", "Bantu (Other)"));
	lang_tbl.push_back(LangTblItem("bos", "bs", "Bosnian"));
	lang_tbl.push_back(LangTblItem("bra", "", "Braj"));
	lang_tbl.push_back(LangTblItem("bre", "br", "Breton"));
	lang_tbl.push_back(LangTblItem("btk", "", "Batak languages"));
	lang_tbl.push_back(LangTblItem("bua", "", "Buriat"));
	lang_tbl.push_back(LangTblItem("bug", "", "Buginese"));
	lang_tbl.push_back(LangTblItem("bul", "bg", "Bulgarian"));
	lang_tbl.push_back(LangTblItem("bur", "my", "Burmese"));
	lang_tbl.push_back(LangTblItem("byn", "", "Blin"));
	lang_tbl.push_back(LangTblItem("byn", "", "Bilin"));
	lang_tbl.push_back(LangTblItem("cad", "", "Caddo"));
	lang_tbl.push_back(LangTblItem("cai", "", "Central American Indian languages"));
	lang_tbl.push_back(LangTblItem("car", "", "Galibi Carib"));
	lang_tbl.push_back(LangTblItem("cat", "ca", "Catalan"));
	lang_tbl.push_back(LangTblItem("cat", "ca", "Valencian"));
	lang_tbl.push_back(LangTblItem("cau", "", "Caucasian languages"));
	lang_tbl.push_back(LangTblItem("ceb", "", "Cebuano"));
	lang_tbl.push_back(LangTblItem("cel", "", "Celtic languages"));
	lang_tbl.push_back(LangTblItem("cha", "ch", "Chamorro"));
	lang_tbl.push_back(LangTblItem("chb", "", "Chibcha"));
	lang_tbl.push_back(LangTblItem("che", "ce", "Chechen"));
	lang_tbl.push_back(LangTblItem("chg", "", "Chagatai"));
	lang_tbl.push_back(LangTblItem("chi", "zh", "Chinese"));
	lang_tbl.push_back(LangTblItem("chk", "", "Chuukese"));
	lang_tbl.push_back(LangTblItem("chm", "", "Mari"));
	lang_tbl.push_back(LangTblItem("chn", "", "Chinook jargon"));
	lang_tbl.push_back(LangTblItem("cho", "", "Choctaw"));
	lang_tbl.push_back(LangTblItem("chp", "", "Chipewyan"));
	lang_tbl.push_back(LangTblItem("chp", "", "Dene Suline"));
	lang_tbl.push_back(LangTblItem("chr", "", "Cherokee"));
	lang_tbl.push_back(LangTblItem("chu", "cu", "Church Slavic"));
	lang_tbl.push_back(LangTblItem("chu", "cu", "Old Slavonic"));
	lang_tbl.push_back(LangTblItem("chu", "cu", "Church Slavonic"));
	lang_tbl.push_back(LangTblItem("chu", "cu", "Old Bulgarian"));
	lang_tbl.push_back(LangTblItem("chu", "cu", "Old Church Slavonic"));
	lang_tbl.push_back(LangTblItem("chv", "cv", "Chuvash"));
	lang_tbl.push_back(LangTblItem("chy", "", "Cheyenne"));
	lang_tbl.push_back(LangTblItem("cmc", "", "Chamic languages"));
	lang_tbl.push_back(LangTblItem("cop", "", "Coptic"));
	lang_tbl.push_back(LangTblItem("cor", "kw", "Cornish"));
	lang_tbl.push_back(LangTblItem("cos", "co", "Corsican"));
	lang_tbl.push_back(LangTblItem("cpe", "", "Creoles and pidgins, English based"));
	lang_tbl.push_back(LangTblItem("cpf", "", "Creoles and pidgins, French-based"));
	lang_tbl.push_back(LangTblItem("cpp", "", "Creoles and pidgins, Portuguese-based"));
	lang_tbl.push_back(LangTblItem("cre", "cr", "Cree"));
	lang_tbl.push_back(LangTblItem("crh", "", "Crimean Tatar"));
	lang_tbl.push_back(LangTblItem("crh", "", "Crimean Turkish"));
	lang_tbl.push_back(LangTblItem("crp", "", "Creoles and pidgins"));
	lang_tbl.push_back(LangTblItem("csb", "", "Kashubian"));
	lang_tbl.push_back(LangTblItem("cus", "", "Cushitic languages"));
	lang_tbl.push_back(LangTblItem("cze", "cs", "Czech"));
	lang_tbl.push_back(LangTblItem("dak", "", "Dakota"));
	lang_tbl.push_back(LangTblItem("dan", "da", "Danish"));
	lang_tbl.push_back(LangTblItem("dar", "", "Dargwa"));
	lang_tbl.push_back(LangTblItem("day", "", "Land Dayak languages"));
	lang_tbl.push_back(LangTblItem("del", "", "Delaware"));
	lang_tbl.push_back(LangTblItem("den", "", "Slave (Athapascan)"));
	lang_tbl.push_back(LangTblItem("dgr", "", "Dogrib"));
	lang_tbl.push_back(LangTblItem("din", "", "Dinka"));
	lang_tbl.push_back(LangTblItem("div", "dv", "Divehi"));
	lang_tbl.push_back(LangTblItem("div", "dv", "Dhivehi"));
	lang_tbl.push_back(LangTblItem("div", "dv", "Maldivian"));
	lang_tbl.push_back(LangTblItem("doi", "", "Dogri"));
	lang_tbl.push_back(LangTblItem("dra", "", "Dravidian languages"));
	lang_tbl.push_back(LangTblItem("dsb", "", "Lower Sorbian"));
	lang_tbl.push_back(LangTblItem("dua", "", "Duala"));
	lang_tbl.push_back(LangTblItem("dum", "", "Dutch, Middle (ca.1050-1350)"));
	lang_tbl.push_back(LangTblItem("dut", "nl", "Dutch"));
	lang_tbl.push_back(LangTblItem("dut", "nl", "Flemish"));
	lang_tbl.push_back(LangTblItem("dyu", "", "Dyula"));
	lang_tbl.push_back(LangTblItem("dzo", "dz", "Dzongkha"));
	lang_tbl.push_back(LangTblItem("efi", "", "Efik"));
	lang_tbl.push_back(LangTblItem("egy", "", "Egyptian (Ancient)"));
	lang_tbl.push_back(LangTblItem("eka", "", "Ekajuk"));
	lang_tbl.push_back(LangTblItem("elx", "", "Elamite"));
	lang_tbl.push_back(LangTblItem("eng", "en", "English"));
	lang_tbl.push_back(LangTblItem("enm", "", "English, Middle (1100-1500)"));
	lang_tbl.push_back(LangTblItem("epo", "eo", "Esperanto"));
	lang_tbl.push_back(LangTblItem("est", "et", "Estonian"));
	lang_tbl.push_back(LangTblItem("ewe", "ee", "Ewe"));
	lang_tbl.push_back(LangTblItem("ewo", "", "Ewondo"));
	lang_tbl.push_back(LangTblItem("fan", "", "Fang"));
	lang_tbl.push_back(LangTblItem("fao", "fo", "Faroese"));
	lang_tbl.push_back(LangTblItem("fat", "", "Fanti"));
	lang_tbl.push_back(LangTblItem("fij", "fj", "Fijian"));
	lang_tbl.push_back(LangTblItem("fil", "", "Filipino"));
	lang_tbl.push_back(LangTblItem("fil", "", "Pilipino"));
	lang_tbl.push_back(LangTblItem("fin", "fi", "Finnish"));
	lang_tbl.push_back(LangTblItem("fiu", "", "Finno-Ugrian languages"));
	lang_tbl.push_back(LangTblItem("fon", "", "Fon"));
	lang_tbl.push_back(LangTblItem("fre", "fr", "French"));
	lang_tbl.push_back(LangTblItem("frm", "", "French, Middle (ca.1400-1600)"));
	lang_tbl.push_back(LangTblItem("fro", "", "French, Old (842-ca.1400)"));
	lang_tbl.push_back(LangTblItem("frr", "", "Northern Frisian"));
	lang_tbl.push_back(LangTblItem("frs", "", "Eastern Frisian"));
	lang_tbl.push_back(LangTblItem("fry", "fy", "Western Frisian"));
	lang_tbl.push_back(LangTblItem("ful", "ff", "Fulah"));
	lang_tbl.push_back(LangTblItem("fur", "", "Friulian"));
	lang_tbl.push_back(LangTblItem("gaa", "", "Ga"));
	lang_tbl.push_back(LangTblItem("gay", "", "Gayo"));
	lang_tbl.push_back(LangTblItem("gba", "", "Gbaya"));
	lang_tbl.push_back(LangTblItem("gem", "", "Germanic languages"));
	lang_tbl.push_back(LangTblItem("geo", "ka", "Georgian"));
	lang_tbl.push_back(LangTblItem("ger", "de", "German"));
	lang_tbl.push_back(LangTblItem("gez", "", "Geez"));
	lang_tbl.push_back(LangTblItem("gil", "", "Gilbertese"));
	lang_tbl.push_back(LangTblItem("gla", "gd", "Gaelic"));
	lang_tbl.push_back(LangTblItem("gla", "gd", "Scottish Gaelic"));
	lang_tbl.push_back(LangTblItem("gle", "ga", "Irish"));
	lang_tbl.push_back(LangTblItem("glg", "gl", "Galician"));
	lang_tbl.push_back(LangTblItem("glv", "gv", "Manx"));
	lang_tbl.push_back(LangTblItem("gmh", "", "German, Middle High (ca.1050-1500)"));
	lang_tbl.push_back(LangTblItem("goh", "", "German, Old High (ca.750-1050)"));
	lang_tbl.push_back(LangTblItem("gon", "", "Gondi"));
	lang_tbl.push_back(LangTblItem("gor", "", "Gorontalo"));
	lang_tbl.push_back(LangTblItem("got", "", "Gothic"));
	lang_tbl.push_back(LangTblItem("grb", "", "Grebo"));
	lang_tbl.push_back(LangTblItem("grc", "", "Greek, Ancient (to 1453)"));
	lang_tbl.push_back(LangTblItem("gre", "el", "Greek, Modern (1453-)"));
	lang_tbl.push_back(LangTblItem("grn", "gn", "Guarani"));
	lang_tbl.push_back(LangTblItem("gsw", "", "Swiss German"));
	lang_tbl.push_back(LangTblItem("gsw", "", "Alemannic"));
	lang_tbl.push_back(LangTblItem("gsw", "", "Alsatian"));
	lang_tbl.push_back(LangTblItem("guj", "gu", "Gujarati"));
	lang_tbl.push_back(LangTblItem("gwi", "", "Gwich'in"));
	lang_tbl.push_back(LangTblItem("hai", "", "Haida"));
	lang_tbl.push_back(LangTblItem("hat", "ht", "Haitian"));
	lang_tbl.push_back(LangTblItem("hat", "ht", "Haitian Creole"));
	lang_tbl.push_back(LangTblItem("hau", "ha", "Hausa"));
	lang_tbl.push_back(LangTblItem("haw", "", "Hawaiian"));
	lang_tbl.push_back(LangTblItem("heb", "he", "Hebrew"));
	lang_tbl.push_back(LangTblItem("her", "hz", "Herero"));
	lang_tbl.push_back(LangTblItem("hil", "", "Hiligaynon"));
	lang_tbl.push_back(LangTblItem("him", "", "Himachali languages"));
	lang_tbl.push_back(LangTblItem("him", "", "Western Pahari languages"));
	lang_tbl.push_back(LangTblItem("hin", "hi", "Hindi"));
	lang_tbl.push_back(LangTblItem("hit", "", "Hittite"));
	lang_tbl.push_back(LangTblItem("hmn", "", "Hmong"));
	lang_tbl.push_back(LangTblItem("hmn", "", "Mong"));
	lang_tbl.push_back(LangTblItem("hmo", "ho", "Hiri Motu"));
	lang_tbl.push_back(LangTblItem("hrv", "hr", "Croatian"));
	lang_tbl.push_back(LangTblItem("hsb", "", "Upper Sorbian"));
	lang_tbl.push_back(LangTblItem("hun", "hu", "Hungarian"));
	lang_tbl.push_back(LangTblItem("hup", "", "Hupa"));
	lang_tbl.push_back(LangTblItem("iba", "", "Iban"));
	lang_tbl.push_back(LangTblItem("ibo", "ig", "Igbo"));
	lang_tbl.push_back(LangTblItem("ice", "is", "Icelandic"));
	lang_tbl.push_back(LangTblItem("ido", "io", "Ido"));
	lang_tbl.push_back(LangTblItem("iii", "ii", "Sichuan Yi"));
	lang_tbl.push_back(LangTblItem("iii", "ii", "Nuosu"));
	lang_tbl.push_back(LangTblItem("ijo", "", "Ijo languages"));
	lang_tbl.push_back(LangTblItem("iku", "iu", "Inuktitut"));
	lang_tbl.push_back(LangTblItem("ile", "ie", "Interlingue"));
	lang_tbl.push_back(LangTblItem("ile", "ie", "Occidental"));
	lang_tbl.push_back(LangTblItem("ilo", "", "Iloko"));
	lang_tbl.push_back(LangTblItem("ina", "ia", "Interlingua (International Auxiliary Language Association)"));
	lang_tbl.push_back(LangTblItem("inc", "", "Indic languages"));
	lang_tbl.push_back(LangTblItem("ind", "id", "Indonesian"));
	lang_tbl.push_back(LangTblItem("ine", "", "Indo-European languages"));
	lang_tbl.push_back(LangTblItem("inh", "", "Ingush"));
	lang_tbl.push_back(LangTblItem("ipk", "ik", "Inupiaq"));
	lang_tbl.push_back(LangTblItem("ira", "", "Iranian languages"));
	lang_tbl.push_back(LangTblItem("iro", "", "Iroquoian languages"));
	lang_tbl.push_back(LangTblItem("ita", "it", "Italian"));
	lang_tbl.push_back(LangTblItem("jav", "jv", "Javanese"));
	lang_tbl.push_back(LangTblItem("jbo", "", "Lojban"));
	lang_tbl.push_back(LangTblItem("jpn", "ja", "Japanese"));
	lang_tbl.push_back(LangTblItem("jpr", "", "Judeo-Persian"));
	lang_tbl.push_back(LangTblItem("jrb", "", "Judeo-Arabic"));
	lang_tbl.push_back(LangTblItem("kaa", "", "Kara-Kalpak"));
	lang_tbl.push_back(LangTblItem("kab", "", "Kabyle"));
	lang_tbl.push_back(LangTblItem("kac", "", "Kachin"));
	lang_tbl.push_back(LangTblItem("kac", "", "Jingpho"));
	lang_tbl.push_back(LangTblItem("kal", "kl", "Kalaallisut"));
	lang_tbl.push_back(LangTblItem("kal", "kl", "Greenlandic"));
	lang_tbl.push_back(LangTblItem("kam", "", "Kamba"));
	lang_tbl.push_back(LangTblItem("kan", "kn", "Kannada"));
	lang_tbl.push_back(LangTblItem("kar", "", "Karen languages"));
	lang_tbl.push_back(LangTblItem("kas", "ks", "Kashmiri"));
	lang_tbl.push_back(LangTblItem("kau", "kr", "Kanuri"));
	lang_tbl.push_back(LangTblItem("kaw", "", "Kawi"));
	lang_tbl.push_back(LangTblItem("kaz", "kk", "Kazakh"));
	lang_tbl.push_back(LangTblItem("kbd", "", "Kabardian"));
	lang_tbl.push_back(LangTblItem("kha", "", "Khasi"));
	lang_tbl.push_back(LangTblItem("khi", "", "Khoisan languages"));
	lang_tbl.push_back(LangTblItem("khm", "km", "Central Khmer"));
	lang_tbl.push_back(LangTblItem("kho", "", "Khotanese"));
	lang_tbl.push_back(LangTblItem("kho", "", "Sakan"));
	lang_tbl.push_back(LangTblItem("kik", "ki", "Kikuyu"));
	lang_tbl.push_back(LangTblItem("kik", "ki", "Gikuyu"));
	lang_tbl.push_back(LangTblItem("kin", "rw", "Kinyarwanda"));
	lang_tbl.push_back(LangTblItem("kir", "ky", "Kirghiz"));
	lang_tbl.push_back(LangTblItem("kir", "ky", "Kyrgyz"));
	lang_tbl.push_back(LangTblItem("kmb", "", "Kimbundu"));
	lang_tbl.push_back(LangTblItem("kok", "", "Konkani"));
	lang_tbl.push_back(LangTblItem("kom", "kv", "Komi"));
	lang_tbl.push_back(LangTblItem("kon", "kg", "Kongo"));
	lang_tbl.push_back(LangTblItem("kor", "ko", "Korean"));
	lang_tbl.push_back(LangTblItem("kos", "", "Kosraean"));
	lang_tbl.push_back(LangTblItem("kpe", "", "Kpelle"));
	lang_tbl.push_back(LangTblItem("krc", "", "Karachay-Balkar"));
	lang_tbl.push_back(LangTblItem("krl", "", "Karelian"));
	lang_tbl.push_back(LangTblItem("kro", "", "Kru languages"));
	lang_tbl.push_back(LangTblItem("kru", "", "Kurukh"));
	lang_tbl.push_back(LangTblItem("kua", "kj", "Kuanyama"));
	lang_tbl.push_back(LangTblItem("kua", "kj", "Kwanyama"));
	lang_tbl.push_back(LangTblItem("kum", "", "Kumyk"));
	lang_tbl.push_back(LangTblItem("kur", "ku", "Kurdish"));
	lang_tbl.push_back(LangTblItem("kut", "", "Kutenai"));
	lang_tbl.push_back(LangTblItem("lad", "", "Ladino"));
	lang_tbl.push_back(LangTblItem("lah", "", "Lahnda"));
	lang_tbl.push_back(LangTblItem("lam", "", "Lamba"));
	lang_tbl.push_back(LangTblItem("lao", "lo", "Lao"));
	lang_tbl.push_back(LangTblItem("lat", "la", "Latin"));
	lang_tbl.push_back(LangTblItem("lav", "lv", "Latvian"));
	lang_tbl.push_back(LangTblItem("lez", "", "Lezghian"));
	lang_tbl.push_back(LangTblItem("lhu", "", "Lahu"));
	lang_tbl.push_back(LangTblItem("lim", "li", "Limburgan"));
	lang_tbl.push_back(LangTblItem("lim", "li", "Limburger"));
	lang_tbl.push_back(LangTblItem("lim", "li", "Limburgish"));
	lang_tbl.push_back(LangTblItem("lin", "ln", "Lingala"));
	lang_tbl.push_back(LangTblItem("lit", "lt", "Lithuanian"));
	lang_tbl.push_back(LangTblItem("lol", "", "Mongo"));
	lang_tbl.push_back(LangTblItem("loz", "", "Lozi"));
	lang_tbl.push_back(LangTblItem("ltz", "lb", "Luxembourgish"));
	lang_tbl.push_back(LangTblItem("ltz", "lb", "Letzeburgesch"));
	lang_tbl.push_back(LangTblItem("lua", "", "Luba-Lulua"));
	lang_tbl.push_back(LangTblItem("lub", "lu", "Luba-Katanga"));
	lang_tbl.push_back(LangTblItem("lug", "lg", "Ganda"));
	lang_tbl.push_back(LangTblItem("lui", "", "Luiseno"));
	lang_tbl.push_back(LangTblItem("lun", "", "Lunda"));
	lang_tbl.push_back(LangTblItem("luo", "", "Luo (Kenya and Tanzania)"));
	lang_tbl.push_back(LangTblItem("lus", "", "Lushai"));
	lang_tbl.push_back(LangTblItem("mac", "mk", "Macedonian"));
	lang_tbl.push_back(LangTblItem("mad", "", "Madurese"));
	lang_tbl.push_back(LangTblItem("mag", "", "Magahi"));
	lang_tbl.push_back(LangTblItem("mah", "mh", "Marshallese"));
	lang_tbl.push_back(LangTblItem("mai", "", "Maithili"));
	lang_tbl.push_back(LangTblItem("mak", "", "Makasar"));
	lang_tbl.push_back(LangTblItem("mal", "ml", "Malayalam"));
	lang_tbl.push_back(LangTblItem("man", "", "Mandingo"));
	lang_tbl.push_back(LangTblItem("mao", "mi", "Maori"));
	lang_tbl.push_back(LangTblItem("map", "", "Austronesian languages"));
	lang_tbl.push_back(LangTblItem("mar", "mr", "Marathi"));
	lang_tbl.push_back(LangTblItem("mas", "", "Masai"));
	lang_tbl.push_back(LangTblItem("may", "ms", "Malay"));
	lang_tbl.push_back(LangTblItem("mdf", "", "Moksha"));
	lang_tbl.push_back(LangTblItem("mdr", "", "Mandar"));
	lang_tbl.push_back(LangTblItem("men", "", "Mende"));
	lang_tbl.push_back(LangTblItem("mga", "", "Irish, Middle (900-1200)"));
	lang_tbl.push_back(LangTblItem("mic", "", "Mi'kmaq"));
	lang_tbl.push_back(LangTblItem("mic", "", "Micmac"));
	lang_tbl.push_back(LangTblItem("min", "", "Minangkabau"));
	lang_tbl.push_back(LangTblItem("mis", "", "Uncoded languages"));
	lang_tbl.push_back(LangTblItem("mkh", "", "Mon-Khmer languages"));
	lang_tbl.push_back(LangTblItem("mlg", "mg", "Malagasy"));
	lang_tbl.push_back(LangTblItem("mlt", "mt", "Maltese"));
	lang_tbl.push_back(LangTblItem("mnc", "", "Manchu"));
	lang_tbl.push_back(LangTblItem("mni", "", "Manipuri"));
	lang_tbl.push_back(LangTblItem("mno", "", "Manobo languages"));
	lang_tbl.push_back(LangTblItem("moh", "", "Mohawk"));
	lang_tbl.push_back(LangTblItem("mon", "mn", "Mongolian"));
	lang_tbl.push_back(LangTblItem("mos", "", "Mossi"));
	lang_tbl.push_back(LangTblItem("mul", "", "Multiple languages"));
	lang_tbl.push_back(LangTblItem("mun", "", "Munda languages"));
	lang_tbl.push_back(LangTblItem("mus", "", "Creek"));
	lang_tbl.push_back(LangTblItem("mwl", "", "Mirandese"));
	lang_tbl.push_back(LangTblItem("mwr", "", "Marwari"));
	lang_tbl.push_back(LangTblItem("mya", "", "Myanmar"));
	lang_tbl.push_back(LangTblItem("myn", "", "Mayan languages"));
	lang_tbl.push_back(LangTblItem("myv", "", "Erzya"));
	lang_tbl.push_back(LangTblItem("nah", "", "Nahuatl languages"));
	lang_tbl.push_back(LangTblItem("nai", "", "North American Indian languages"));
	lang_tbl.push_back(LangTblItem("nap", "", "Neapolitan"));
	lang_tbl.push_back(LangTblItem("nau", "na", "Nauru"));
	lang_tbl.push_back(LangTblItem("nav", "nv", "Navajo"));
	lang_tbl.push_back(LangTblItem("nav", "nv", "Navaho"));
	lang_tbl.push_back(LangTblItem("nbl", "nr", "Ndebele, South"));
	lang_tbl.push_back(LangTblItem("nbl", "nr", "South Ndebele"));
	lang_tbl.push_back(LangTblItem("nde", "nd", "Ndebele, North"));
	lang_tbl.push_back(LangTblItem("nde", "nd", "North Ndebele"));
	lang_tbl.push_back(LangTblItem("ndo", "ng", "Ndonga"));
	lang_tbl.push_back(LangTblItem("nds", "", "Low German"));
	lang_tbl.push_back(LangTblItem("nds", "", "Low Saxon"));
	lang_tbl.push_back(LangTblItem("nds", "", "German, Low"));
	lang_tbl.push_back(LangTblItem("nds", "", "Saxon, Low"));
	lang_tbl.push_back(LangTblItem("nep", "ne", "Nepali"));
	lang_tbl.push_back(LangTblItem("new", "", "Nepal Bhasa"));
	lang_tbl.push_back(LangTblItem("new", "", "Newari"));
	lang_tbl.push_back(LangTblItem("nia", "", "Nias"));
	lang_tbl.push_back(LangTblItem("nic", "", "Niger-Kordofanian languages"));
	lang_tbl.push_back(LangTblItem("niu", "", "Niuean"));
	lang_tbl.push_back(LangTblItem("nno", "nn", "Norwegian Nynorsk"));
	lang_tbl.push_back(LangTblItem("nno", "nn", "Nynorsk, Norwegian"));
	lang_tbl.push_back(LangTblItem("nob", "nb", "Bokm\303\245l, Norwegian"));
	lang_tbl.push_back(LangTblItem("nob", "nb", "Norwegian Bokm\303\245l"));
	lang_tbl.push_back(LangTblItem("nog", "", "Nogai"));
	lang_tbl.push_back(LangTblItem("non", "", "Norse, Old"));
	lang_tbl.push_back(LangTblItem("nor", "no", "Norwegian"));
	lang_tbl.push_back(LangTblItem("nqo", "", "N'Ko"));
	lang_tbl.push_back(LangTblItem("nso", "", "Pedi"));
	lang_tbl.push_back(LangTblItem("nso", "", "Sepedi"));
	lang_tbl.push_back(LangTblItem("nso", "", "Northern Sotho"));
	lang_tbl.push_back(LangTblItem("nub", "", "Nubian languages"));
	lang_tbl.push_back(LangTblItem("nwc", "", "Classical Newari"));
	lang_tbl.push_back(LangTblItem("nwc", "", "Old Newari"));
	lang_tbl.push_back(LangTblItem("nwc", "", "Classical Nepal Bhasa"));
	lang_tbl.push_back(LangTblItem("nya", "ny", "Chichewa"));
	lang_tbl.push_back(LangTblItem("nya", "ny", "Chewa"));
	lang_tbl.push_back(LangTblItem("nya", "ny", "Nyanja"));
	lang_tbl.push_back(LangTblItem("nym", "", "Nyamwezi"));
	lang_tbl.push_back(LangTblItem("nyn", "", "Nyankole"));
	lang_tbl.push_back(LangTblItem("nyo", "", "Nyoro"));
	lang_tbl.push_back(LangTblItem("nzi", "", "Nzima"));
	lang_tbl.push_back(LangTblItem("oci", "oc", "Occitan (post 1500)"));
	lang_tbl.push_back(LangTblItem("oci", "oc", "Proven\303\247al"));
	lang_tbl.push_back(LangTblItem("oji", "oj", "Ojibwa"));
	lang_tbl.push_back(LangTblItem("ori", "or", "Oriya"));
	lang_tbl.push_back(LangTblItem("orm", "om", "Oromo"));
	lang_tbl.push_back(LangTblItem("osa", "", "Osage"));
	lang_tbl.push_back(LangTblItem("oss", "os", "Ossetian"));
	lang_tbl.push_back(LangTblItem("oss", "os", "Ossetic"));
	lang_tbl.push_back(LangTblItem("ota", "", "Turkish, Ottoman (1500-1928)"));
	lang_tbl.push_back(LangTblItem("oto", "", "Otomian languages"));
	lang_tbl.push_back(LangTblItem("paa", "", "Papuan languages"));
	lang_tbl.push_back(LangTblItem("pag", "", "Pangasinan"));
	lang_tbl.push_back(LangTblItem("pal", "", "Pahlavi"));
	lang_tbl.push_back(LangTblItem("pam", "", "Pampanga"));
	lang_tbl.push_back(LangTblItem("pam", "", "Kapampangan"));
	lang_tbl.push_back(LangTblItem("pan", "pa", "Panjabi"));
	lang_tbl.push_back(LangTblItem("pan", "pa", "Punjabi"));
	lang_tbl.push_back(LangTblItem("pap", "", "Papiamento"));
	lang_tbl.push_back(LangTblItem("pau", "", "Palauan"));
	lang_tbl.push_back(LangTblItem("peo", "", "Persian, Old (ca.600-400 B.C.)"));
	lang_tbl.push_back(LangTblItem("per", "fa", "Persian"));
	lang_tbl.push_back(LangTblItem("phi", "", "Philippine languages"));
	lang_tbl.push_back(LangTblItem("phn", "", "Phoenician"));
	lang_tbl.push_back(LangTblItem("pli", "pi", "Pali"));
	lang_tbl.push_back(LangTblItem("pol", "pl", "Polish"));
	lang_tbl.push_back(LangTblItem("pon", "", "Pohnpeian"));
	lang_tbl.push_back(LangTblItem("por", "pt", "Portuguese"));
	lang_tbl.push_back(LangTblItem("pra", "", "Prakrit languages"));
	lang_tbl.push_back(LangTblItem("pro", "", "Proven\303\247al, Old (to 1500)"));
	lang_tbl.push_back(LangTblItem("pus", "ps", "Pushto"));
	lang_tbl.push_back(LangTblItem("pus", "ps", "Pashto"));
	lang_tbl.push_back(LangTblItem("que", "qu", "Quechua"));
	lang_tbl.push_back(LangTblItem("raj", "", "Rajasthani"));
	lang_tbl.push_back(LangTblItem("rap", "", "Rapanui"));
	lang_tbl.push_back(LangTblItem("rar", "", "Rarotongan"));
	lang_tbl.push_back(LangTblItem("rar", "", "Cook Islands Maori"));
	lang_tbl.push_back(LangTblItem("roa", "", "Romance languages"));
	lang_tbl.push_back(LangTblItem("roh", "rm", "Romansh"));
	lang_tbl.push_back(LangTblItem("rom", "", "Romany"));
	lang_tbl.push_back(LangTblItem("rum", "ro", "Romanian"));
	lang_tbl.push_back(LangTblItem("rum", "ro", "Moldavian"));
	lang_tbl.push_back(LangTblItem("rum", "ro", "Moldovan"));
	lang_tbl.push_back(LangTblItem("run", "rn", "Rundi"));
	lang_tbl.push_back(LangTblItem("rup", "", "Aromanian"));
	lang_tbl.push_back(LangTblItem("rup", "", "Arumanian"));
	lang_tbl.push_back(LangTblItem("rup", "", "Macedo-Romanian"));
	lang_tbl.push_back(LangTblItem("rus", "ru", "Russian"));
	lang_tbl.push_back(LangTblItem("sad", "", "Sandawe"));
	lang_tbl.push_back(LangTblItem("sag", "sg", "Sango"));
	lang_tbl.push_back(LangTblItem("sah", "", "Yakut"));
	lang_tbl.push_back(LangTblItem("sai", "", "South American Indian (Other)"));
	lang_tbl.push_back(LangTblItem("sal", "", "Salishan languages"));
	lang_tbl.push_back(LangTblItem("sam", "", "Samaritan Aramaic"));
	lang_tbl.push_back(LangTblItem("san", "sa", "Sanskrit"));
	lang_tbl.push_back(LangTblItem("sas", "", "Sasak"));
	lang_tbl.push_back(LangTblItem("sat", "", "Santali"));
	lang_tbl.push_back(LangTblItem("scn", "", "Sicilian"));
	lang_tbl.push_back(LangTblItem("sco", "", "Scots"));
	lang_tbl.push_back(LangTblItem("sel", "", "Selkup"));
	lang_tbl.push_back(LangTblItem("sem", "", "Semitic languages"));
	lang_tbl.push_back(LangTblItem("sga", "", "Irish, Old (to 900)"));
	lang_tbl.push_back(LangTblItem("sgn", "", "Sign Languages"));
	lang_tbl.push_back(LangTblItem("shn", "", "Shan"));
	lang_tbl.push_back(LangTblItem("sid", "", "Sidamo"));
	lang_tbl.push_back(LangTblItem("sin", "si", "Sinhala"));
	lang_tbl.push_back(LangTblItem("sin", "si", "Sinhalese"));
	lang_tbl.push_back(LangTblItem("sio", "", "Siouan languages"));
	lang_tbl.push_back(LangTblItem("sit", "", "Sino-Tibetan languages"));
	lang_tbl.push_back(LangTblItem("sla", "", "Slavic languages"));
	lang_tbl.push_back(LangTblItem("slo", "sk", "Slovak"));
	lang_tbl.push_back(LangTblItem("slv", "sl", "Slovenian"));
	lang_tbl.push_back(LangTblItem("sma", "", "Southern Sami"));
	lang_tbl.push_back(LangTblItem("sme", "se", "Northern Sami"));
	lang_tbl.push_back(LangTblItem("smi", "", "Sami languages"));
	lang_tbl.push_back(LangTblItem("smj", "", "Lule Sami"));
	lang_tbl.push_back(LangTblItem("smn", "", "Inari Sami"));
	lang_tbl.push_back(LangTblItem("smo", "sm", "Samoan"));
	lang_tbl.push_back(LangTblItem("sms", "", "Skolt Sami"));
	lang_tbl.push_back(LangTblItem("sna", "sn", "Shona"));
	lang_tbl.push_back(LangTblItem("snd", "sd", "Sindhi"));
	lang_tbl.push_back(LangTblItem("snk", "", "Soninke"));
	lang_tbl.push_back(LangTblItem("sog", "", "Sogdian"));
	lang_tbl.push_back(LangTblItem("som", "so", "Somali"));
	lang_tbl.push_back(LangTblItem("son", "", "Songhai languages"));
	lang_tbl.push_back(LangTblItem("sot", "st", "Sotho, Southern"));
	lang_tbl.push_back(LangTblItem("spa", "es", "Spanish"));
	lang_tbl.push_back(LangTblItem("spa", "es", "Castilian"));
	lang_tbl.push_back(LangTblItem("srd", "sc", "Sardinian"));
	lang_tbl.push_back(LangTblItem("srn", "", "Sranan Tongo"));
	lang_tbl.push_back(LangTblItem("srp", "sr", "Serbian"));
	lang_tbl.push_back(LangTblItem("srr", "", "Serer"));
	lang_tbl.push_back(LangTblItem("ssa", "", "Nilo-Saharan languages"));
	lang_tbl.push_back(LangTblItem("ssw", "ss", "Swati"));
	lang_tbl.push_back(LangTblItem("suk", "", "Sukuma"));
	lang_tbl.push_back(LangTblItem("sun", "su", "Sundanese"));
	lang_tbl.push_back(LangTblItem("sus", "", "Susu"));
	lang_tbl.push_back(LangTblItem("sux", "", "Sumerian"));
	lang_tbl.push_back(LangTblItem("swa", "sw", "Swahili"));
	lang_tbl.push_back(LangTblItem("swe", "sv", "Swedish"));
	lang_tbl.push_back(LangTblItem("syc", "", "Classical Syriac"));
	lang_tbl.push_back(LangTblItem("syr", "", "Syriac"));
	lang_tbl.push_back(LangTblItem("tah", "ty", "Tahitian"));
	lang_tbl.push_back(LangTblItem("tai", "", "Tai languages"));
	lang_tbl.push_back(LangTblItem("tam", "ta", "Tamil"));
	lang_tbl.push_back(LangTblItem("tat", "tt", "Tatar"));
	lang_tbl.push_back(LangTblItem("tel", "te", "Telugu"));
	lang_tbl.push_back(LangTblItem("tem", "", "Timne"));
	lang_tbl.push_back(LangTblItem("ter", "", "Tereno"));
	lang_tbl.push_back(LangTblItem("tet", "", "Tetum"));
	lang_tbl.push_back(LangTblItem("tgk", "tg", "Tajik"));
	lang_tbl.push_back(LangTblItem("tgl", "tl", "Tagalog"));
	lang_tbl.push_back(LangTblItem("tha", "th", "Thai"));
	lang_tbl.push_back(LangTblItem("tib", "bo", "Tibetan"));
	lang_tbl.push_back(LangTblItem("tig", "", "Tigre"));
	lang_tbl.push_back(LangTblItem("tir", "ti", "Tigrinya"));
	lang_tbl.push_back(LangTblItem("tiv", "", "Tiv"));
	lang_tbl.push_back(LangTblItem("tkl", "", "Tokelau"));
	lang_tbl.push_back(LangTblItem("tlh", "", "Klingon"));
	lang_tbl.push_back(LangTblItem("tlh", "", "tlhIngan-Hol"));
	lang_tbl.push_back(LangTblItem("tli", "", "Tlingit"));
	lang_tbl.push_back(LangTblItem("tmh", "", "Tamashek"));
	lang_tbl.push_back(LangTblItem("tog", "", "Tonga (Nyasa)"));
	lang_tbl.push_back(LangTblItem("ton", "to", "Tonga (Tonga Islands)"));
	lang_tbl.push_back(LangTblItem("tpi", "", "Tok Pisin"));
	lang_tbl.push_back(LangTblItem("tsi", "", "Tsimshian"));
	lang_tbl.push_back(LangTblItem("tsn", "tn", "Tswana"));
	lang_tbl.push_back(LangTblItem("tso", "ts", "Tsonga"));
	lang_tbl.push_back(LangTblItem("tuk", "tk", "Turkmen"));
	lang_tbl.push_back(LangTblItem("tum", "", "Tumbuka"));
	lang_tbl.push_back(LangTblItem("tup", "", "Tupi languages"));
	lang_tbl.push_back(LangTblItem("tur", "tr", "Turkish"));
	lang_tbl.push_back(LangTblItem("tut", "", "Altaic languages"));
	lang_tbl.push_back(LangTblItem("tvl", "", "Tuvalu"));
	lang_tbl.push_back(LangTblItem("twi", "tw", "Twi"));
	lang_tbl.push_back(LangTblItem("tyv", "", "Tuvinian"));
	lang_tbl.push_back(LangTblItem("udm", "", "Udmurt"));
	lang_tbl.push_back(LangTblItem("uga", "", "Ugaritic"));
	lang_tbl.push_back(LangTblItem("uig", "ug", "Uighur"));
	lang_tbl.push_back(LangTblItem("uig", "ug", "Uyghur"));
	lang_tbl.push_back(LangTblItem("ukr", "uk", "Ukrainian"));
	lang_tbl.push_back(LangTblItem("umb", "", "Umbundu"));
	lang_tbl.push_back(LangTblItem("und", "", "Undetermined"));
	lang_tbl.push_back(LangTblItem("urd", "ur", "Urdu"));
	lang_tbl.push_back(LangTblItem("uzb", "uz", "Uzbek"));
	lang_tbl.push_back(LangTblItem("vai", "", "Vai"));
	lang_tbl.push_back(LangTblItem("ven", "ve", "Venda"));
	lang_tbl.push_back(LangTblItem("vie", "vi", "Vietnamese"));
	lang_tbl.push_back(LangTblItem("vol", "vo", "Volap\303\274k"));
	lang_tbl.push_back(LangTblItem("vot", "", "Votic"));
	lang_tbl.push_back(LangTblItem("wak", "", "Wakashan languages"));
	lang_tbl.push_back(LangTblItem("wal", "", "Walamo"));
	lang_tbl.push_back(LangTblItem("war", "", "Waray"));
	lang_tbl.push_back(LangTblItem("was", "", "Washo"));
	lang_tbl.push_back(LangTblItem("wel", "cy", "Welsh"));
	lang_tbl.push_back(LangTblItem("wen", "", "Sorbian languages"));
	lang_tbl.push_back(LangTblItem("wln", "wa", "Walloon"));
	lang_tbl.push_back(LangTblItem("wol", "wo", "Wolof"));
	lang_tbl.push_back(LangTblItem("xal", "", "Kalmyk"));
	lang_tbl.push_back(LangTblItem("xal", "", "Oirat"));
	lang_tbl.push_back(LangTblItem("xho", "xh", "Xhosa"));
	lang_tbl.push_back(LangTblItem("yao", "", "Yao"));
	lang_tbl.push_back(LangTblItem("yap", "", "Yapese"));
	lang_tbl.push_back(LangTblItem("yid", "yi", "Yiddish"));
	lang_tbl.push_back(LangTblItem("yor", "yo", "Yoruba"));
	lang_tbl.push_back(LangTblItem("ypk", "", "Yupik languages"));
	lang_tbl.push_back(LangTblItem("zap", "", "Zapotec"));
	lang_tbl.push_back(LangTblItem("zbl", "", "Blissymbols"));
	lang_tbl.push_back(LangTblItem("zbl", "", "Blissymbolics"));
	lang_tbl.push_back(LangTblItem("zbl", "", "Bliss"));
	lang_tbl.push_back(LangTblItem("zen", "", "Zenaga"));
	lang_tbl.push_back(LangTblItem("zha", "za", "Zhuang"));
	lang_tbl.push_back(LangTblItem("zha", "za", "Chuang"));
	lang_tbl.push_back(LangTblItem("znd", "", "Zande languages"));
	lang_tbl.push_back(LangTblItem("zul", "zu", "Zulu"));
	lang_tbl.push_back(LangTblItem("zun", "", "Zuni"));
	lang_tbl.push_back(LangTblItem("zxx", "", "No linguistic content"));
	lang_tbl.push_back(LangTblItem("zxx", "", "Not applicable"));
	lang_tbl.push_back(LangTblItem("zza", "", "Zaza"));
	lang_tbl.push_back(LangTblItem("zza", "", "Dimili"));
	lang_tbl.push_back(LangTblItem("zza", "", "Dimli"));
	lang_tbl.push_back(LangTblItem("zza", "", "Kirdki"));
	lang_tbl.push_back(LangTblItem("zza", "", "Kirmanjki"));
	lang_tbl.push_back(LangTblItem("zza", "", "Zazaki"));
}

